# DEMO#3 - Re-run with randint and unique indices per random subset...

# DEMO#2 - Expand Experiments...

# DEMO#1 - 01/31/2024 - See https://jh-ml.nccs.nasa.gov/jupyterhub-prism/user/gtamkin/lab/workspaces/auto-0/tree/_AGB-dev/mpf-model-factories/MultiPathFusion/multi_path_fusion/notebooks/glenn/gt_mc_get_stats.ipynb

# Generate Permutation Importance (i.e., rank) from SHAP files

In [1]:
import shap
import numpy as np
import pickle
import glob
import pandas as pd
import subprocess
import csv
from pathlib import Path

In [2]:
def format_band_set(subset):
    indexListIntStr = ''
    count = 0
    for band in subset:
        if (count == 0):
            indexListIntStr = indexListIntStr + str(band)
        else:
            indexListIntStr = indexListIntStr + ', ' + str(band)
        count = count + 1
    return indexListIntStr


# Read from CSV

In [3]:
hyperspectral_aggregate_bandnames = '/explore/nobackup/projects/ilab/data/AGB/test/mcruns/input/bands/MLBS_2018_541567.6_4136443.0_542567.6_4137443.0-hyperspectral-aggregate-bandnames.csv'
only_row = None
with open(hyperspectral_aggregate_bandnames) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        only_row = row
        print(row[0])
        print(row[446])
#print(only_row)

ARI
2511.7


In [4]:
# initialize list of lists
headers = ['Group','Top10Index','Top10Rank','Top10Value','Scaling','Randomizer', '#Bands','#Trials','Band/Trial','MinBands','hh:mm:ss.ms','Host(s)','CPUs/Host','Concurrency','ResultDir','ID','Description','HF', 'Callbacks']
site = 'MLBS_2018_541567.6_4136443.0_542567.6_4137443.0'

## Read batch of shap files for experiment, which contains run-time artifacts (e.g., SHAP values)

In [5]:
root_data_path = '/explore/nobackup/projects/ilab/data/AGB/test/mcruns/output'

In [98]:
#headers = ['Group','Top10Index','Top10Rank','Scaling','Randomizer', '#Bands','#Trials','Band/Trial','MinBands','hh:mm:ss.ms','Host(s)','CPUs/Host','Concurrency','ResultDir','ID','Description','HF', 'Callbacks']
permutation_results_VI_3trials = [
     ['V1b1','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '188', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI_randintU_20240302_188_20m_3b','575050868397492482', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb1','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '191', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI_randintU_20240302_191_20m_3b','972812867574749608', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb1','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '193', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI_randintU_20240302_193_20m_3b','853379430912402815', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb1','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '200', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI_randintU_20240302_200_20m_3b','875083503082867641', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb1','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '214', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI_randintU_20240302_214_20m_3b','279550132438151710', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb1','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '225', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI_randintU_20240302_225_20m_3b','424433684070503325', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb1','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '230', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI_randintU_20240302_230_20m_3b','500424548463509068', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb1','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '247', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI_randintU_20240302_247_20m_3b','498345501911623626', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
#    
      ['VIb2','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '188', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI/VI_randintU_20240302_188_20m_3b','575050868397492482', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb2','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '191', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI/VI_randintU_20240302_191_20m_3b','806398069851382119', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb2','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '193', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI/VI_randintU_20240302_193_20m_3b','874529206487521041', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb2','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '200', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI/VI_randintU_20240302_200_20m_3b','965060104529880310', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb2','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '214', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI/VI_randintU_20240302_214_20m_3b','728278796873995749', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb2','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '225', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI/VI_randintU_20240302_225_20m_3b','514050032010718833', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb2','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '230', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI/VI_randintU_20240302_230_20m_3b','360349938924147892', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb2','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '247', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI/VI_randintU_20240302_247_20m_3b','214107507827042739', 'VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
#    
      ['VIb3','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '188', '3', '20','~0:27:00.00','gpu002','40','Pool', 
       'VI/VI_randintU_20240303_188_20m_3b','898188862101410804', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb3','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '191', '3', '20','~0:27:00.00','gpu002','40','Pool', 
       'VI/VI_randintU_20240303_191_20m_3b','101554869495136186', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb3','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '193', '3', '20','~0:27:00.00','gpu002','40','Pool', 
       'VI/VI_randintU_20240303_193_20m_3b','261914886327368313', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb3','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '200', '3', '20','~0:27:00.00','gpu002','40','Pool', 
       'VI/VI_randintU_20240303_200_20m_3b','552713534466588559', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb3','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '214', '3', '20','~0:27:00.00','gpu002','40','Pool', 
       'VI/VI_randintU_20240303_214_20m_3b','121679581342470880', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb3','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '225', '3', '20','~0:27:00.00','gpu002','40','Pool', 
       'VI/VI_randintU_20240303_225_20m_3b','664133247155684072', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb3','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '230', '3', '20','~0:27:00.00','gpu002','40','Pool', 
       'VI/VI_randintU_20240303_230_20m_3b','131603933973007654', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VIb3','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '247', '3', '20','~0:27:00.00','gpu007','40','Pool', 
       'VI/VI_randintU_20240303_247_20m_3b','120201914459639429', '## VI - 20 minimum occurrences, 3 bands per trial',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],

]

In [99]:
#headers = ['Group','Top10Index','Top10Rank','Scaling','Randomizer', '#Bands','#Trials','Band/Trial','MinBands','hh:mm:ss.ms','Host(s)','CPUs/Host','Concurrency','ResultDir','ID','Description','HF', 'Callbacks']
permutation_results_VI = [
     ['VI','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '32', '10', '10','0:27:25.246467','ilab213','30','Pool', 
       'VI_randint_U_20240229_6','891516017211874507', '## VI - ilab213:  Time elapsed on node [ilab213] = (hh:mm:ss.ms) 0:27:25.246467',
       'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VI','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '32', '10', '10','0:26:36.387707','ilab213','30','Pool', 
      'VI_randint_U_20240229_5','345536919353575236', '## VI - ilab213:  Time elapsed on node [ilab213] = (hh:mm:ss.ms) 0:26:36.387707',
      'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VI','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '32', '10', '10','0:25:12.317','ilab213','30','Pool', 
      'VI_randint_U_20240229_4','673843053471350852', '## VI - ilab213:  Time elapsed on node [ilab213] = (hh:mm:ss.ms) 0:25:12.317',
      'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VI','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '32', '10', '10','0:26:52.317282','ilab213','30','Pool', 
      'VI_randint_U_20240229_3','548764528868727045', '## VI - ilab213:  Time elapsed on node [ilab213] = (hh:mm:ss.ms) 0:26:52.317282',
      'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VI','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '32', '10', '10','0:26:56.519002','ilab213','30','Pool', 
      'VI_randint_U_20240229_2','711241757083075094', '## VI - ilab213:  Time elapsed on node [ilab213] = (hh:mm:ss.ms) 0:26:56.519002',
      'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
     ['VI','NoTop10Index', 'Top10Rank', 'Top10Value','DivBy10K','randitU','21', '32', '10', '10','0:27:43.264823','ilab213','30','Pool', 
      'VI_randint_U_20240229_1','711241757083075094', '## VI - ilab213:  Time elapsed on node [ilab213] = (hh:mm:ss.ms) 0:27:43.264823',
      'MLBS_2018_hyperspectral_indices.tif','EarlyWarning'],
]

In [100]:
#headers = ['Group','Top10Index','Top10Rank','Scaling','Randomizer', '#Bands','#Trials','Band/Trial','MinBands','hh:mm:ss.ms','Host(s)','CPUs/Host','Concurrency','ResultDir','ID','Description','HF', 'Callbacks']
permutation_results_ALL = [
     ['_ALL','NoTop10Index', 'Top10Rank', 'DivBy10K','randit','447', '1088', '10', '50','??:13:25','ilab213','40','Pool', 
      'random_sets_20240227_shrink_False_num_samples_1088_bandLen_447','784143931214701529', 
      'ALL - min 50 occurrences: ~?? hours',
      'MLBS_2018_541567.6_4136443.0_542567.6_4137443.0-hyperspectral-aggregate.separate-background-scaled.tif ','EarlyWarning'],    
]

In [101]:
#headers = ['Group','Top10Index','Top10Rank','Scaling','Randomizer', '#Bands','#Trials','Band/Trial','MinBands','hh:mm:ss.ms','Host(s)','CPUs/Host','Concurrency','ResultDir','ID','Description','HF', 'Callbacks']
permutation_results_NEON = [
     ['_NEON','NoTop10Index', 'Top10Rank', 'DivBy10K','randit','426', '1079', '10', '10', '07:00.00','gpu004','40','Pool', 
      'randint_sets_20240225_collection-NEON_min_occurrences-10_batch_size-10_num_samples-1080_bandLen-426','188577871478003488', 
      'NEON on gpu004 - min 10 occurrences: ~7hours',
      'MLBS_2018_Reflectance_reflectance_warp_scaled.tif','EarlyWarning'],
]


In [102]:
#permutation_results = permutation_results_ALL
#permutation_results = permutation_results_VI
#permutation_results = permutation_results_NEON
#permutation_results = permutation_results_ALL + permutation_results_NEON + permutation_results_VI
#permutation_results = permutation_results_ALL + permutation_results_NEON + permutation_results_VI
permutation_results = permutation_results_VI_3trials

print(len(permutation_results), '\n',permutation_results)

24 
 [['V1b1', 'NoTop10Index', 'Top10Rank', 'Top10Value', 'DivBy10K', 'randitU', '21', '188', '3', '20', '~0:27:00.00', 'gpu007', '40', 'Pool', 'VI_randintU_20240302_188_20m_3b', '575050868397492482', '## VI - 20 minimum occurrences, 3 bands per trial', 'MLBS_2018_hyperspectral_indices.tif', 'EarlyWarning'], ['VIb1', 'NoTop10Index', 'Top10Rank', 'Top10Value', 'DivBy10K', 'randitU', '21', '191', '3', '20', '~0:27:00.00', 'gpu007', '40', 'Pool', 'VI_randintU_20240302_191_20m_3b', '972812867574749608', '## VI - 20 minimum occurrences, 3 bands per trial', 'MLBS_2018_hyperspectral_indices.tif', 'EarlyWarning'], ['VIb1', 'NoTop10Index', 'Top10Rank', 'Top10Value', 'DivBy10K', 'randitU', '21', '193', '3', '20', '~0:27:00.00', 'gpu007', '40', 'Pool', 'VI_randintU_20240302_193_20m_3b', '853379430912402815', '## VI - 20 minimum occurrences, 3 bands per trial', 'MLBS_2018_hyperspectral_indices.tif', 'EarlyWarning'], ['VIb1', 'NoTop10Index', 'Top10Rank', 'Top10Value', 'DivBy10K', 'randitU', '21', '

In [103]:
# Create the pandas DataFrame
df = pd.DataFrame(permutation_results, columns=headers)
df

Group Top10Index    Top10Rank  Top10Value  Scaling   Randomizer #Bands  \
0   V1b1  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
1   VIb1  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
2   VIb1  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
3   VIb1  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
4   VIb1  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
5   VIb1  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
6   VIb1  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
7   VIb1  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
8   VIb2  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
9   VIb2  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
10  VIb2  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
11  VIb2  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
12  VIb2  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
13  VIb2  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
14  VIb2  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
15  VIb2  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
16  VIb3  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
17  VIb3  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
18  VIb3  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
19  VIb3  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
20  VIb3  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
21  VIb3  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
22  VIb3  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      
23  VIb3  NoTop10Index  Top10Rank  Top10Value  DivBy10K  randitU    21      

   #Trials Band/Trial MinBands hh:mm:ss.ms  Host(s) CPUs/Host Concurrency  \
0   188     3          20       ~0:27:00.00  gpu007  40        Pool         
1   191     3          20       ~0:27:00.00  gpu007  40        Pool         
2   193     3          20       ~0:27:00.00  gpu007  40        Pool         
3   200     3          20       ~0:27:00.00  gpu007  40        Pool         
4   214     3          20       ~0:27:00.00  gpu007  40        Pool         
5   225     3          20       ~0:27:00.00  gpu007  40        Pool         
6   230     3          20       ~0:27:00.00  gpu007  40        Pool         
7   247     3          20       ~0:27:00.00  gpu007  40        Pool         
8   188     3          20       ~0:27:00.00  gpu007  40        Pool         
9   191     3          20       ~0:27:00.00  gpu007  40        Pool         
10  193     3          20       ~0:27:00.00  gpu007  40        Pool         
11  200     3          20       ~0:27:00.00  gpu007  40        Pool         
12  214     3          20       ~0:27:00.00  gpu007  40        Pool         
13  225     3          20       ~0:27:00.00  gpu007  40        Pool         
14  230     3          20       ~0:27:00.00  gpu007  40        Pool         
15  247     3          20       ~0:27:00.00  gpu007  40        Pool         
16  188     3          20       ~0:27:00.00  gpu002  40        Pool         
17  191     3          20       ~0:27:00.00  gpu002  40        Pool         
18  193     3          20       ~0:27:00.00  gpu002  40        Pool         
19  200     3          20       ~0:27:00.00  gpu002  40        Pool         
20  214     3          20       ~0:27:00.00  gpu002  40        Pool         
21  225     3          20       ~0:27:00.00  gpu002  40        Pool         
22  230     3          20       ~0:27:00.00  gpu002  40        Pool         
23  247     3          20       ~0:27:00.00  gpu007  40        Pool         

   ResultDir                           ID                   \
0      VI_randintU_20240302_188_20m_3b  575050868397492482   
1      VI_randintU_20240302

# Loop through result files and create the ranking

In [104]:
#. Loop through result files and create the ranking
for r_index, row in df.iterrows():
#    rank_file = '/explore/nobackup/projects/ilab/data/AGB/test/mcruns/output/rank/' + df.at[r_index,'ResultDir'] + '.rank' 
    rank_file = '/explore/nobackup/projects/ilab/data/AGB/test/mcruns/output/rank/VI-20min-3trials/' + df.at[r_index,'ResultDir'] + '.rank' 
    my_file = Path(rank_file)
    if my_file.is_file():
        bandAbsSumArr = pickle.load(open(rank_file, "rb"))
        print('\n ======== index[', r_index, '] ==========')
        print('Loaded:', rank_file)
    else:
        shap_dir_prefix = root_data_path + '/' + df.at[r_index,'ResultDir'] + '/' + df.at[r_index,'ID'] 
        shap_dir = shap_dir_prefix + '/PERMUTATION_IMPORTANCE_VALUES/'
        print('\n ======== index[', r_index, '] ==========')
        print(r_index,'index: ', shap_dir)

        # Returns a list of names in list files. 
        shap_files = glob.glob(shap_dir + '**/*.shap_values0to50',  
                           recursive = True) 

        # set to max number of hyperspectral indices in experiment
        bandLen = int(df.at[r_index,'#Bands'])
        bandOccurenceArr = np.zeros(bandLen).astype(int)
        bandAbsSumArr = np.zeros(bandLen)

        first_time = True
        index = 0
        # Reload config
        start = left = '[['
        end = right = ']]'

        for shap_vals_path in shap_files:

            index = index+1
            num_shap_files = len(shap_files)
            bandListStr = shap_vals_path[shap_vals_path.index(left)+len(left):shap_vals_path.index(right)]
            bandList = [e for e in bandListStr.split(',')]
            for bandNum in bandList:
                bandOccurenceArr[int(bandNum)-1] = (bandOccurenceArr[int(bandNum)-1]) + 1

            # Reload shap values
            shap_values0to50 = pickle.load(open(shap_vals_path, "rb"))
            num_bins = len(shap_values0to50)
            num_rows = len(shap_values0to50[0])
            num_bands = num_cols = len(shap_values0to50[0][0])

            #  Walk across bins [0,4]
            for _bin in range(0, num_bins):

                # get absolute value of all values in matrix
                shap_values0to50_bin_abs = np.abs(shap_values0to50[_bin])

                # convert numpy matrix to dataframe and print sum of absolute values in each column
                df_shap_values0to50_bin_abs = pd.DataFrame(data=shap_values0to50_bin_abs)

                # create a row (numpy array) where each column is the sum of the absolute values in that vertical column
                shap_values_abs_sum_axis0 = np.sum(df_shap_values0to50_bin_abs, axis=0)

                # sort the row from low to high to determine the rank of the columns (e.g., features)
                shap_values_abs_sum_argsort = np.argsort(shap_values_abs_sum_axis0)

                # loop thru each column and update the corresponding statistics in the global row
                for _col in range(0, num_cols):
                    bandNum = int(bandList[_col])

                    # add the absolute value of the current shape_value to the existing value in the cell that is indexed by the band number
                    # this allows us to keep a running total shap values per feature for downselection later....
                    bandAbsSumArr[bandNum-1] = (bandAbsSumArr[bandNum-1] + df_shap_values0to50_bin_abs[_col].sum())

        print('Summary array before sort:', bandAbsSumArr)
        ascending_indices = np.argsort(bandAbsSumArr)[:10]
        print('Top ten before after:', ascending_indices)
        minIndex = ascending_indices[0]

        descending_indices = np.argsort(bandAbsSumArr)[::-1][:10]
        maxIndex = descending_indices[0]

        pickle.dump(bandAbsSumArr, open(rank_file , "wb"))
        print('Saved:', rank_file)
        
    with np.printoptions(precision=5, suppress=True):
#        print('Final:', bandAbsSumArr[:10])
        print('Final.min:', bandAbsSumArr.min(), 'Final.max:', bandAbsSumArr.max())
        print('Final L->H:', np.argsort(bandAbsSumArr)[:10])
        row['Top10Index'] = np.argsort(bandAbsSumArr)[::-1][:10]

        indexList = np.argsort(bandAbsSumArr)[::-1][:10]
        bandList = []
        valueList = []
        for index in range(0, 10):
            bandList.append(str(only_row[indexList[index]]))
            valueList.append(str("{:3.3f}".format(bandAbsSumArr[indexList[index]])))
            print(indexList[index], only_row[indexList[index]],"{:3.3f}".format(bandAbsSumArr[indexList[index]]))        
            index = index + 1
        row['Top10Rank'] = bandList
        row['Top10Value'] = valueList

        print('Final Top10Rank Names:', bandList )
        print('Final Top10Rank Indices:', row['Top10Index'] )
        print('Final Top10Rank Cummulative Absolute SHAP values:', valueList)
        print('Final max:', row['Top10Index'][0])


 ======== index[ 0 ] ==========
Loaded: /explore/nobackup/projects/ilab/data/AGB/test/mcruns/output/rank/VI-20min-3trials/VI_randintU_20240302_188_20m_3b.rank
Final.min: 0.002742228160301139 Final.max: 45.76161194691996
Final L->H: [ 1  2  0 16 11 17  3 19 12 14]
15 NIRv 45.762
6 fPAR 6.442
7 LAI 4.465
8 MCTI 1.017
4 EVI 0.278
5 EVI2 0.251
13 NDVI 0.245
18 SAVI 0.224
10 NDII 0.173
9 MSI 0.133
Final Top10Rank Names: ['NIRv', 'fPAR', 'LAI', 'MCTI', 'EVI', 'EVI2', 'NDVI', 'SAVI', 'NDII', 'MSI']
Final Top10Rank Indices: [15  6  7  8  4  5 13 18 10  9]
Final Top10Rank Cummulative Absolute SHAP values: ['45.762', '6.442', '4.465', '1.017', '0.278', '0.251', '0.245', '0.224', '0.173', '0.133']
Final max: 15

 ======== index[ 1 ] ==========
Loaded: /explore/nobackup/projects/ilab/data/AGB/test/mcruns/output/rank/VI-20min-3trials/VI_randintU_20240302_191_20m_3b.rank
Final.min: 0.0027673583723057675 Final.max: 45.03944486482001
Final L->H: [ 1  2  0 11 16 17  3 19 12 20]
15 NIRv 45.039
7 LAI 10

In [105]:
dfTest = df
dfTest

Group Top10Index                           \
0   V1b1  [15, 6, 7, 8, 4, 5, 13, 18, 10, 9]   
1   VIb1  [15, 7, 6, 8, 5, 4, 18, 13, 9, 10]   
2   VIb1  [15, 7, 6, 8, 5, 18, 13, 4, 9, 10]   
3   VIb1  [15, 6, 8, 7, 4, 5, 18, 13, 10, 9]   
4   VIb1  [15, 6, 8, 7, 5, 13, 4, 18, 9, 14]   
5   VIb1  [15, 6, 7, 8, 4, 18, 5, 13, 10, 9]   
6   VIb1  [15, 7, 8, 6, 5, 13, 18, 4, 9, 10]   
7   VIb1  [15, 7, 6, 8, 5, 4, 18, 9, 10, 13]   
8   VIb2     [20, 9, 1, 2, 3, 4, 5, 6, 7, 8]   
9   VIb2  [15, 7, 6, 8, 4, 5, 18, 13, 9, 10]   
10  VIb2  [15, 6, 7, 8, 5, 18, 13, 4, 9, 10]   
11  VIb2  [15, 6, 8, 7, 4, 5, 13, 18, 10, 9]   
12  VIb2  [15, 6, 8, 7, 5, 13, 4, 9, 18, 10]   
13  VIb2  [15, 7, 8, 4, 5, 6, 18, 13, 9, 10]   
14  VIb2  [15, 7, 6, 8, 4, 5, 18, 9, 13, 10]   
15  VIb2  [15, 7, 8, 6, 5, 4, 18, 9, 10, 13]   
16  VIb3  [15, 7, 8, 6, 5, 18, 13, 4, 9, 10]   
17  VIb3  [15, 7, 8, 4, 6, 5, 18, 13, 9, 10]   
18  VIb3  [15, 7, 8, 5, 18, 13, 4, 6, 10, 9]   
19  VIb3  [15, 6, 7, 8, 4, 5, 18, 13, 10, 9]   
20  VIb3  [15, 6, 8, 7, 5, 13, 4, 9, 18, 10]   
21  VIb3  [15, 7, 6, 8, 4, 18, 5, 13, 9, 10]   
22  VIb3  [15, 6, 7, 8, 5, 18, 4, 13, 9, 10]   
23  VIb3  [15, 7, 8, 4, 18, 5, 6, 10, 9, 13]   

   Top10Rank                                                        \
0        [NIRv, fPAR, LAI, MCTI, EVI, EVI2, NDVI, SAVI, NDII, MSI]   
1        [NIRv, LAI, fPAR, MCTI, EVI2, EVI, SAVI, NDVI, MSI, NDII]   
2        [NIRv, LAI, fPAR, MCTI, EVI2, SAVI, NDVI, EVI, MSI, NDII]   
3        [NIRv, fPAR, MCTI, LAI, EVI, EVI2, SAVI, NDVI, NDII, MSI]   
4        [NIRv, fPAR, MCTI, LAI, EVI2, NDVI, EVI, SAVI, MSI, NDWI]   
5        [NIRv, fPAR, LAI, MCTI, EVI, SAVI, EVI2, NDVI, NDII, MSI]   
6        [NIRv, LAI, MCTI, fPAR, EVI2, NDVI, SAVI, EVI, MSI, NDII]   
7        [NIRv, LAI, fPAR, MCTI, EVI2, EVI, SAVI, MSI, NDII, NDVI]   
8   [Albedo, MSI, CAI, CRI550, CRI700, EVI, EVI2, fPAR, LAI, MCTI]   
9        [NIRv, LAI, fPAR, MCTI, EVI, EVI2, SAVI, NDVI, MSI, NDII]   
10       [NIRv, fPAR, LAI, MCTI, EVI2, SAVI, NDVI, EVI, MSI, NDII]   
11       [NIRv, fPAR, MCTI, LAI, EVI, EVI2, NDVI, SAVI, NDII, MSI]   
12       [NIRv, fPAR, MCTI, LAI, EVI2, NDVI, EVI, MSI, SAVI, NDII]   
13       [NIRv, LAI, MCTI, EVI, EVI2, fPAR, SAVI, NDVI, MSI, NDII]   
14       [NIRv, LAI, fPAR, MCTI, EVI, EVI2, SAVI, MSI, NDVI, NDII]   
15       [NIRv, LAI, MCTI, fPAR, EVI2, EVI, SAVI, MSI, NDII, NDVI]   
16       [NIRv, LAI, MCTI, fPAR, EVI2, SAVI, NDVI, EVI, MSI, NDII]   
17       [NIRv, LAI, MCTI, EVI, fPAR, EVI2, SAVI, NDVI, MSI, NDII]   
18       [NIRv, LAI, MCTI, EVI2, SAVI, NDVI, EVI, fPAR, NDII, MSI]   
19       [NIRv, fPAR, LAI, MCTI, EVI, EVI2, SAVI, NDVI, NDII, MSI]   
20       [NIRv, fPAR, MCTI, LAI, EVI2, NDVI, EVI, MSI, SAVI, NDII]   
21       [NIRv, LAI, fPAR, MCTI, EVI, SAVI, EVI2, NDVI, MSI, NDII]   
22       [NIRv, fPAR, LAI, MCTI, EVI2, SAVI, EVI, NDVI, MSI, NDII]   
23       [NIRv, LAI, MCTI, EVI, SAVI, EVI2, fPAR, NDII, MSI, NDVI]   

   Top10Value                                                                 \
0    [45.762, 6.442, 4.465, 1.017, 0.278, 0.251, 0.245, 0.224, 0.173, 0.133]   
1   [45.039, 10.946, 6.594, 1.353, 0.308, 0.270, 0.239, 0.186, 0.162, 0.119]   
2    [57.775, 7.435, 3.428, 2.450, 0.266, 0.261, 0.232, 0.222, 0.147, 0.111]   
3    [66.467, 3.432, 1.845, 1.524, 0.419, 0.347, 0.232, 0.196, 0.154, 0.130]   
4    [42.074, 3.579, 1.988, 1.476, 0.331, 0.242, 0.221, 0.185, 0.179, 0.085]   
5   [39.497, 22.109, 8.253, 3.168, 0.440, 0.333, 0.328, 0.255, 0.117, 0.108]   
6    [50.083, 4.324, 3.603, 3.408, 0.395, 0.310, 0.292, 0.283, 0.245, 0.115]   
7   [61.073, 18.378, 9.598, 3.218, 0.415, 0.394, 0.357, 0.236, 0.227, 0.186]   
8     [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]   
9    [42.507, 7.506, 6.588, 1.875, 0.278, 0.275, 0.237, 0.184, 0.168, 0.156]   
10   [79.761, 9.482, 7.729, 1.969, 0.311, 0.293, 0.238, 0.227, 0.110, 0.109]   
11   [36.916, 9.667, 2.187, 1.741, 0.399, 0.381, 0.250, 0.190, 0.126, 0.117]   
12   [49.39

In [106]:
print('[ID]-[Group]-[Min]-[Band]-[Trials]-[Scaling]-[Top 10 Rank]-[Top 10 Indices]-[Randomizer]')
#headers = ['Group','Top10Index','Top10Rank','Scaling','Randomizer', '#Bands','#Trials','Band/Trial','MinBands','hh:mm:ss.ms','Host(s)','CPUs/Host','Concurrency','ResultDir','ID','Description','HF', 'Callbacks']
for index, row in df.iterrows():
    print('', str(index).rjust(2), '-',row['Group'].rjust(4),'-', row['MinBands'].rjust(3), '-', row['#Bands'].rjust(3),'-', row['#Trials'].rjust(4), '-', row['Scaling'].rjust(8), '-', row['Top10Rank'], '-', row['Top10Index'], '-', row['Randomizer'])

[ID]-[Group]-[Min]-[Band]-[Trials]-[Scaling]-[Top 10 Rank]-[Top 10 Indices]-[Randomizer]
  0 - V1b1 -  20 -  21 -  188 - DivBy10K - ['NIRv', 'fPAR', 'LAI', 'MCTI', 'EVI', 'EVI2', 'NDVI', 'SAVI', 'NDII', 'MSI'] - [15  6  7  8  4  5 13 18 10  9] - randitU
  1 - VIb1 -  20 -  21 -  191 - DivBy10K - ['NIRv', 'LAI', 'fPAR', 'MCTI', 'EVI2', 'EVI', 'SAVI', 'NDVI', 'MSI', 'NDII'] - [15  7  6  8  5  4 18 13  9 10] - randitU
  2 - VIb1 -  20 -  21 -  193 - DivBy10K - ['NIRv', 'LAI', 'fPAR', 'MCTI', 'EVI2', 'SAVI', 'NDVI', 'EVI', 'MSI', 'NDII'] - [15  7  6  8  5 18 13  4  9 10] - randitU
  3 - VIb1 -  20 -  21 -  200 - DivBy10K - ['NIRv', 'fPAR', 'MCTI', 'LAI', 'EVI', 'EVI2', 'SAVI', 'NDVI', 'NDII', 'MSI'] - [15  6  8  7  4  5 18 13 10  9] - randitU
  4 - VIb1 -  20 -  21 -  214 - DivBy10K - ['NIRv', 'fPAR', 'MCTI', 'LAI', 'EVI2', 'NDVI', 'EVI', 'SAVI', 'MSI', 'NDWI'] - [15  6  8  7  5 13  4 18  9 14] - randitU
  5 - VIb1 -  20 -  21 -  225 - DivBy10K - ['NIRv', 'fPAR', 'LAI', 'MCTI', 'EVI', 'SAV

In [111]:
pd.set_option('max_colwidth', 800)
pd.set_option('display.colheader_justify', 'left')
dfSummary = df[['Group','MinBands','Band/Trial','#Trials','#Bands','Randomizer','Scaling','Top10Rank','Top10Value']] 
dfSummary.style.set_properties(**{'text-align': 'left'})
dfSummary

Group MinBands Band/Trial #Trials #Bands Randomizer Scaling    \
0   V1b1  20       3          188     21     randitU    DivBy10K   
1   VIb1  20       3          191     21     randitU    DivBy10K   
2   VIb1  20       3          193     21     randitU    DivBy10K   
3   VIb1  20       3          200     21     randitU    DivBy10K   
4   VIb1  20       3          214     21     randitU    DivBy10K   
5   VIb1  20       3          225     21     randitU    DivBy10K   
6   VIb1  20       3          230     21     randitU    DivBy10K   
7   VIb1  20       3          247     21     randitU    DivBy10K   
8   VIb2  20       3          188     21     randitU    DivBy10K   
9   VIb2  20       3          191     21     randitU    DivBy10K   
10  VIb2  20       3          193     21     randitU    DivBy10K   
11  VIb2  20       3          200     21     randitU    DivBy10K   
12  VIb2  20       3          214     21     randitU    DivBy10K   
13  VIb2  20       3          225     21     randitU    DivBy10K   
14  VIb2  20       3          230     21     randitU    DivBy10K   
15  VIb2  20       3          247     21     randitU    DivBy10K   
16  VIb3  20       3          188     21     randitU    DivBy10K   
17  VIb3  20       3          191     21     randitU    DivBy10K   
18  VIb3  20       3          193     21     randitU    DivBy10K   
19  VIb3  20       3          200     21     randitU    DivBy10K   
20  VIb3  20       3          214     21     randitU    DivBy10K   
21  VIb3  20       3          225     21     randitU    DivBy10K   
22  VIb3  20       3          230     21     randitU    DivBy10K   
23  VIb3  20       3          247     21     randitU    DivBy10K   

   Top10Rank                                                        \
0        [NIRv, fPAR, LAI, MCTI, EVI, EVI2, NDVI, SAVI, NDII, MSI]   
1        [NIRv, LAI, fPAR, MCTI, EVI2, EVI, SAVI, NDVI, MSI, NDII]   
2        [NIRv, LAI, fPAR, MCTI, EVI2, SAVI, NDVI, EVI, MSI, NDII]   
3        [NIRv, fPAR, MCTI, LAI, EVI, EVI2, SAVI, NDVI, NDII, MSI]   
4        [NIRv, fPAR, MCTI, LAI, EVI2, NDVI, EVI, SAVI, MSI, NDWI]   
5        [NIRv, fPAR, LAI, MCTI, EVI, SAVI, EVI2, NDVI, NDII, MSI]   
6        [NIRv, LAI, MCTI, fPAR, EVI2, NDVI, SAVI, EVI, MSI, NDII]   
7        [NIRv, LAI, fPAR, MCTI, EVI2, EVI, SAVI, MSI, NDII, NDVI]   
8   [Albedo, MSI, CAI, CRI550, CRI700, EVI, EVI2, fPAR, LAI, MCTI]   
9        [NIRv, LAI, fPAR, MCTI, EVI, EVI2, SAVI, NDVI, MSI, NDII]   
10       [NIRv, fPAR, LAI, MCTI, EVI2, SAVI, NDVI, EVI, MSI, NDII]   
11       [NIRv, fPAR, MCTI, LAI, EVI, EVI2, NDVI, SAVI, NDII, MSI]   
12       [NIRv, fPAR, MCTI, LAI, EVI2, NDVI, EVI, MSI, SAVI, NDII]   
13       [NIRv, LAI, MCTI, EVI, EVI2, fPAR, SAVI, NDVI, MSI, NDII]   
14       [NIRv, LAI, fPAR, MCTI, EVI, EVI2, SAVI, MSI, NDVI, NDII]   
15       [NIRv, LAI, MCTI, fPAR, EVI2, EVI, SAVI, MSI, NDII, NDVI]   
16       [NIRv, LAI, MCTI, fPAR, EVI2, SAVI, NDVI, EVI, MSI, NDII]   
17       [NIRv, LAI, MCTI, EVI, fPAR, EVI2, SAVI, NDVI, MSI, NDII]   
18       [NIRv, LAI, MCTI, EVI2, SAVI, NDVI, EVI, fPAR, NDII, MSI]   
19       [NIRv, fPAR, LAI, MCTI, EVI, EVI2, SAVI, NDVI, NDII, MSI]   
20       [NIRv, fPAR, MCTI, LAI, EVI2, NDVI, EVI, MSI, SAVI, NDII]   
21       [NIRv, LAI, fPAR, MCTI, EVI, SAVI, EVI2, NDVI, MSI, NDII]   
22       [NIRv, fPAR, LAI, MCTI, EVI2, SAVI, EVI, NDVI, MSI, NDII]   
23       [NIRv, LAI, MCTI, EVI, SAVI, EVI2, fPAR, NDII, MSI, NDVI]   

   Top10Value                                                                 
0    [45.762, 6.442, 4.465, 1.017, 0.278, 0.251, 0.245, 0.224, 0.173, 0.133]  
1   [45.039, 10.946, 6.594, 1.353, 0.308, 0.270, 0.239, 0.186, 0.162, 0.119]  
2    [57.775, 7.435, 3.428, 2.450, 0.266, 0.261, 0.232, 0.222, 0.147, 0.111]  
3    [66.467, 3.432, 1.845, 1.524, 0.419, 0.347, 0.232, 0.196, 0.154, 0.130]  
4    [42.074, 3.579, 1.988, 1.476, 0.331, 0.242, 0.221, 0.185, 0.179, 0.085]  
5   [39.497, 22.109, 8.253, 3.168, 0.440, 0.333, 0.328, 0.255, 0.117, 0.108] 

In [108]:
from pandas import DataFrame
def left_align(df: DataFrame):
    left_aligned_df = df.style.set_properties(**{'text-align': 'left'})
    left_aligned_df = left_aligned_df.set_table_styles(
        [dict(selector='th', props=[('text-align', 'left')])]
    )
    return left_aligned_df


In [109]:
left_align(dfSummary)

## +++++++++

In [46]:
random_set_path = '/explore/nobackup/projects/ilab/data/AGB/test/mcruns/input/random_sets/randint_sets_20240301_collection-VI_min_occurrences-20_batch_size-3_num_samples-188_bandLen-21.pkl'
random_set_rows = pickle.load(open(random_set_path, "rb"))
num_bins = len(random_set_rows)
num_rows = len(random_set_rows[0])
num_bands = num_cols = len(random_set_rows[0][0])
print (random_set_path, num_bins, num_rows, num_bands,num_cols, '\n', random_set_rows[0])

/explore/nobackup/projects/ilab/data/AGB/test/mcruns/input/random_sets/randint_sets_20240301_collection-VI_min_occurrences-20_batch_size-3_num_samples-188_bandLen-21.pkl 188 3 1 1 
 ['1', '21', '14']


In [81]:
df_random_set_rows = pd.DataFrame(data=random_set_rows)
df_random_set_rows.head()
print(list(df_random_set_rows.columns))
df_random_set_rows_sorted0 = df_random_set_rows.sort_values(0, ascending=True)
df_random_set_rows_sorted1 = df_random_set_rows_sorted0.sort_values(1, ascending=True)
df_random_set_rows_sorted2 = df_random_set_rows_sorted1.sort_values(2, ascending=True)
df_random_set_rows_sorted123 = df_random_set_rows.sort_values(by = [0, 1,2 ], ascending = [True, True, True])

df_random_set_rows_sorted = df_random_set_rows_sorted123
#sorted_df = df_random_set_rows.sort_values(by = [0, 1], ascending = [True, True])
#print(sorted_df)
with pd.option_context('display.max_rows', None,):
#     print(sorted_df)
     print(df_random_set_rows_sorted.head())

[0, 1, 2]
    0  1   2  
53   1  16  21
120  1  19  14
45   1   2   4
0    1  21  14
143  1   3   9


In [84]:
df_random_set_rows_sorted0

0  1   2  
0    1  21  14
53   1  16  21
110  1   5  16
36   1   6   7
143  1   3   9
..  ..  ..  ..
59   9  19  12
121  9  21  20
103  9  13   1
1    9  21   7
85   9  10   6

[188 rows x 3 columns]

In [85]:
# Find Duplicate rows
with pd.option_context('display.max_rows', None,):
    #print(df_random_set_rows.groupby(df_random_set_rows.columns.tolist(),as_index=False).size())
    print(df_random_set_rows.value_counts().head())

0   1   2 
2   15  18    2
19  4   18    2
4   1   2     1
3   12  16    1
3   12  18    1
dtype: int64


In [88]:
shap_vals_path = '/explore/nobackup/projects/ilab/data/AGB/test/mcruns/output/VI_randintU_20240302_188_20m_3b/575050868397492482/PERMUTATION_IMPORTANCE_VALUES/MLP_SGD_7_layers_1024_units_MAE_50_epochs_callbacks::575050868397492482.keras[[1, 2, 4]].shap_values0to50'
shap_values0to50 = pickle.load(open(shap_vals_path, "rb"))
num_bins = len(shap_values0to50)
num_rows = len(shap_values0to50[0])
num_bands = num_cols = len(shap_values0to50[0][0])
print (shap_vals_path, num_bins, num_rows, num_bands,num_cols, '\n', shap_values0to50[0])

/explore/nobackup/projects/ilab/data/AGB/test/mcruns/output/VI_randintU_20240302_188_20m_3b/575050868397492482/PERMUTATION_IMPORTANCE_VALUES/MLP_SGD_7_layers_1024_units_MAE_50_epochs_callbacks::575050868397492482.keras[[1, 2, 4]].shap_values0to50 5 50 3 3 
 [[ 7.69992669e-07  1.00036462e-07 -6.93957011e-06]
 [ 2.03003486e-06  2.69313653e-07 -1.47912900e-05]
 [ 3.70492538e-07  1.87953313e-07 -3.34973137e-06]
 [ 9.95248556e-07  9.44733620e-08 -6.71222806e-06]
 [-1.40815973e-06 -7.40587712e-08  1.21615827e-05]
 [-1.73866749e-06 -1.71363354e-07  1.46457553e-05]
 [ 3.16798687e-07 -2.35289335e-07 -2.60457397e-06]
 [-3.02096208e-07 -2.37425168e-08 -3.65575155e-08]
 [-1.80453062e-06 -8.52346420e-08  1.37016177e-05]
 [ 1.40925248e-06  3.56485446e-07 -1.28569702e-05]
 [ 9.58492359e-07  6.27835592e-08 -5.86892168e-06]
 [-5.79555829e-07  1.16477410e-07  1.18846695e-06]
 [-2.55852938e-07 -1.86562538e-07  1.45092607e-06]
 [ 2.02208757e-07 -5.06639482e-09  1.22860074e-06]
 [ 2.54710515e-07 -3.8395325

In [89]:
shap_values0to50_bin = shap_values0to50[_bin]
df_shap_values0to50_bin = pd.DataFrame(data=shap_values0to50_bin)
df_shap_values0to50_bin

0             1             2           
0   1.478195e-07  7.405877e-08 -7.034093e-06
1   3.995001e-07  1.856685e-07 -1.469895e-05
2   6.248554e-08  1.314779e-07 -3.474603e-06
3   1.880030e-07  6.685654e-08 -6.813755e-06
4  -2.714495e-07 -5.433957e-08  1.230394e-05
5  -3.313025e-07 -1.258155e-07  1.489396e-05
6   5.011757e-08 -1.690785e-07 -2.729545e-06
7  -6.169081e-08 -1.505017e-08 -1.640618e-07
8  -3.476938e-07 -6.382664e-08  1.390959e-05
9   2.709031e-07  2.452731e-07 -1.282692e-05
10  1.869102e-07  4.862746e-08 -5.974869e-06
11 -1.171728e-07  8.786718e-08  1.070003e-06
12 -5.399187e-08 -1.347562e-07  1.333753e-06
13  2.955397e-08 -5.612771e-09  1.106163e-06
14  4.669031e-08 -2.632538e-08 -9.615223e-07
15 -6.447732e-07 -1.983345e-07  2.279013e-05
16  1.375874e-08 -9.099642e-08  1.252045e-06
17 -5.910794e-08  3.804763e-08 -2.644459e-07
18  8.627772e-08  2.376735e-07 -6.733835e-06
19  2.230207e-07 -5.682309e-08 -1.299848e-05
20  2.256533e-07  5.533298e-08 -1.010324e-05
21 -2.852082e-07  7.748604e-08  1.141101e-05
22 -1.769761e-07 -6.074707e-08  7.358094e-06
23  7.440646e-08 -2.736847e-08 -3.864119e-06
24  2.350410e-07 -2.678732e-07 -6.719778e-06
25 -2.889335e-07 -1.381338e-07  1.301616e-05
26 -1.555681e-07  6.675720e-08  4.616380e-06
27  7.892648e-08 -1.968940e-07 -1.583149e-06
28  2.779563e-07 -2.483527e-08 -1.114825e-05
29 -6.313125e-08 -1.081328e-07  4.743536e-06
30  1.299878e-07  2.044936e-07 -9.188155e-06
31 -9.000301e-08 -1.817942e-08  2.653897e-06
32 -3.582736e-07  1.361469e-07  1.708786e-05
33  3.428260e-07  2.234677e-07 -1.552944e-05
34 -6.039937e-08  1.401703e-07 -3.503760e-07
35  1.443426e-07  7.549922e-08 -6.331702e-06
36  1.837810e-08  2.299746e-08 -2.413044e-06
37 -6.793439e-07 -1.043081e-08  2.433553e-05
38  4.440546e-08  8.061528e-08 -8.277595e-07
39 -2.781550e-07 -1.313786e-07  1.265590e-05
40 -1.662970e-07 -1.204014e-07  8.196831e-06
41  2.549589e-07 -1.689792e-07 -3.903061e-06
42  3.775458e-07  1.695255e-07 -1.023521e-05
43 -4.778306e-08 -1.157324e-07  6.076892e-06
44  1.051525e-07  9.054939e-08 -3.774365e-06
45 -2.031525e-08 -1.244744e-07  1.289795e-06
46  9.462237e-08 -1.513958e-07  1.246482e-06
47  5.339583e-07  1.840790e-07 -1.977901e-05
48 -9.914239e-08 -3.640850e-08 -2.727856e-06
49 -6.357829e-09 -2.021591e-08 -2.142290e-07

In [38]:
shap_values0to50_bin = shap_values0to50[_bin]
df_shap_values0to50_bin = pd.DataFrame(data=shap_values0to50_bin)
df_shap_values0to50_bin

0         1             2         3         4             5             \
0  -0.000049  0.000000e+00 -0.000044 -0.000007  0.000000e+00  0.000000e+00   
1  -0.000086  0.000000e+00 -0.000086 -0.000011 -2.504587e-06  0.000000e+00   
2   0.000022  0.000000e+00  0.000023  0.000004  0.000000e+00  0.000000e+00   
3   0.000011  0.000000e+00  0.000007  0.000004  0.000000e+00 -4.911234e-06   
4  -0.000006  0.000000e+00 -0.000006  0.000005 -7.034228e-06 -1.888156e-06   
5   0.000071  0.000000e+00  0.000070  0.000004  4.264736e-06  1.968602e-06   
6   0.000147  6.936972e-07  0.000152  0.000019  2.443971e-07  0.000000e+00   
7   0.000072  0.000000e+00  0.000075  0.000006  4.969408e-06  1.756437e-06   
8  -0.000213  0.000000e+00 -0.000218 -0.000021 -1.733255e-05 -5.582354e-07   
9  -0.000058  0.000000e+00 -0.000056 -0.000005 -3.361417e-06  0.000000e+00   
10  0.000066  6.610001e-07  0.000065  0.000004  4.108145e-06  1.832107e-06   
11  0.000065  0.000000e+00  0.000061  0.000010  0.000000e+00  0.000000e+00   
12 -0.000085  0.000000e+00 -0.000085 -0.000015  8.035810e-06  3.925793e-06   
13 -0.000042  0.000000e+00 -0.000037 -0.000006  0.000000e+00  0.000000e+00   
14  0.000085  9.715016e-07  0.000088  0.000009  1.151476e-06  9.772376e-07   
15  0.000057  1.321466e-07  0.000062  0.000004  3.458662e-06  1.091103e-06   
16 -0.000099  0.000000e+00 -0.000098 -0.000015  9.241959e-06  0.000000e+00   
17  0.000000  0.000000e+00  0.000006  0.000005 -5.406279e-06 -2.652329e-06   
18  0.000124  0.000000e+00  0.000127  0.000016  3.162778e-06  0.000000e+00   
19  0.000020  0.000000e+00  0.000021  0.000005  0.000000e+00  0.000000e+00   
20 -0.000004  0.000000e+00 -0.000007 -0.000005  4.806714e-06  0.000000e+00   
21  0.000096  0.000000e+00  0.000096  0.000010  4.877020e-06  0.000000e+00   
22 -0.000043  0.000000e+00 -0.000044 -0.000002 -7.685223e-06  0.000000e+00   
23  0.000193  1.376198e-07  0.000193  0.000023  1.113422e-07  0.000000e+00   
24  0.000306  4.617632e-07  0.000302  0.000039  1.441127e-06  0.000000e+00   
25  0.000049  0.000000e+00  0.000051  0.000004  2.936334e-06  0.000000e+00   
26 -0.000359 -7.373136e-06 -0.000377 -0.000047  1.328313e-05  0.000000e+00   
27  0.000053  0.000000e+00  0.000052  0.000006  0.000000e+00 -3.174258e-06   
28  0.000048  0.000000e+00  0.000046  0.000009 -4.565310e-06  0.000000e+00   
29 -0.000117  0.000000e+00 -0.000121 -0.000008 -1.118658e-05 -2.049068e-06   
30  0.000173  0.000000e+00  0.000172  0.000024  0.000000e+00  0.000000e+00   
31 -0.000296  0.000000e+00 -0.000307 -0.000036 -5.796872e-06  0.000000e+00   
32  0.000104  5.762256e-07  0.000104  0.000010  4.162412e-06  1.293949e-06   
33  0.000145  0.000000e+00  0.000145  0.000014  2.721619e-06  2.830923e-06   
34  0.000139  0.000000e+00  0.000139  0.000015  2.294258e-06  5.126760e-07   
35  0.000136  1.032527e-06  0.000138  0.000013  4.738482e-06  3.253764e-06   
36 -0.000129  0.000000e+00 -0.000129 -0.000011 -8.476017e-06 -3.108691e-06   
37 -0.000032  0.000000e+00 -0.000030 -0.000008  4.754137e-06  0.000000e+00   
38  0.000003  0.000000e+00  0.000000  0.000000  0.000000e+00  0.000000e+00   
39 -0.000343 -1.048779e-06 -0.000382 -0.000047 -9.331533e-06  0.000000e+00   
40 -0.000028  0.000000e+00 -0.000030 -0.000004  4.699156e-06  0.000000e+00   
41  0.000105  0.000000e+00  0.000106  0.000009  6.763957e-06  0.000000e+00   
42  0.000167  6.599825e-07  0.000167  0.000014  6.883745e-06  4.602999e-06   
43 -0.000115  0.000000e+00 -0.000124 -0.000010 -7.850431e-06 -5.518837e-06   
44 -0.000157  0.000000e+00 -0.000157 -0.000017  0.000000e+00  0.000000e+00   
45  0.000061  2.543672e-07  0.000066  0.000006  1.885118e-06  2.582865e-06   
46 -0.000080  0.000000e+00 -0.000080 -0.000011  5.415133e-06  0.000000e+00   
47  0.000118  0.000000e+00  0.000113  0.000014  0.000000e+00 -4.612672e-06   
48 -0.000417 -4.594909e-06 -0.000351 -0.000027 -1.844510e-05 -1.006521e-06   
49  0.000120  0.000000e+00  0.000124  0.000013  3.939430e-06  0.000000e+00   

    6             7      

In [39]:
shap_values0to50_bin_abs = np.abs(shap_values0to50[_bin])
df_shap_values0to50_bin_abs = pd.DataFrame(data=shap_values0to50_bin_abs)
df_shap_values0to50_bin_abs

0         1             2         3         4             5             \
0   0.000049  0.000000e+00  0.000044  0.000007  0.000000e+00  0.000000e+00   
1   0.000086  0.000000e+00  0.000086  0.000011  2.504587e-06  0.000000e+00   
2   0.000022  0.000000e+00  0.000023  0.000004  0.000000e+00  0.000000e+00   
3   0.000011  0.000000e+00  0.000007  0.000004  0.000000e+00  4.911234e-06   
4   0.000006  0.000000e+00  0.000006  0.000005  7.034228e-06  1.888156e-06   
5   0.000071  0.000000e+00  0.000070  0.000004  4.264736e-06  1.968602e-06   
6   0.000147  6.936972e-07  0.000152  0.000019  2.443971e-07  0.000000e+00   
7   0.000072  0.000000e+00  0.000075  0.000006  4.969408e-06  1.756437e-06   
8   0.000213  0.000000e+00  0.000218  0.000021  1.733255e-05  5.582354e-07   
9   0.000058  0.000000e+00  0.000056  0.000005  3.361417e-06  0.000000e+00   
10  0.000066  6.610001e-07  0.000065  0.000004  4.108145e-06  1.832107e-06   
11  0.000065  0.000000e+00  0.000061  0.000010  0.000000e+00  0.000000e+00   
12  0.000085  0.000000e+00  0.000085  0.000015  8.035810e-06  3.925793e-06   
13  0.000042  0.000000e+00  0.000037  0.000006  0.000000e+00  0.000000e+00   
14  0.000085  9.715016e-07  0.000088  0.000009  1.151476e-06  9.772376e-07   
15  0.000057  1.321466e-07  0.000062  0.000004  3.458662e-06  1.091103e-06   
16  0.000099  0.000000e+00  0.000098  0.000015  9.241959e-06  0.000000e+00   
17  0.000000  0.000000e+00  0.000006  0.000005  5.406279e-06  2.652329e-06   
18  0.000124  0.000000e+00  0.000127  0.000016  3.162778e-06  0.000000e+00   
19  0.000020  0.000000e+00  0.000021  0.000005  0.000000e+00  0.000000e+00   
20  0.000004  0.000000e+00  0.000007  0.000005  4.806714e-06  0.000000e+00   
21  0.000096  0.000000e+00  0.000096  0.000010  4.877020e-06  0.000000e+00   
22  0.000043  0.000000e+00  0.000044  0.000002  7.685223e-06  0.000000e+00   
23  0.000193  1.376198e-07  0.000193  0.000023  1.113422e-07  0.000000e+00   
24  0.000306  4.617632e-07  0.000302  0.000039  1.441127e-06  0.000000e+00   
25  0.000049  0.000000e+00  0.000051  0.000004  2.936334e-06  0.000000e+00   
26  0.000359  7.373136e-06  0.000377  0.000047  1.328313e-05  0.000000e+00   
27  0.000053  0.000000e+00  0.000052  0.000006  0.000000e+00  3.174258e-06   
28  0.000048  0.000000e+00  0.000046  0.000009  4.565310e-06  0.000000e+00   
29  0.000117  0.000000e+00  0.000121  0.000008  1.118658e-05  2.049068e-06   
30  0.000173  0.000000e+00  0.000172  0.000024  0.000000e+00  0.000000e+00   
31  0.000296  0.000000e+00  0.000307  0.000036  5.796872e-06  0.000000e+00   
32  0.000104  5.762256e-07  0.000104  0.000010  4.162412e-06  1.293949e-06   
33  0.000145  0.000000e+00  0.000145  0.000014  2.721619e-06  2.830923e-06   
34  0.000139  0.000000e+00  0.000139  0.000015  2.294258e-06  5.126760e-07   
35  0.000136  1.032527e-06  0.000138  0.000013  4.738482e-06  3.253764e-06   
36  0.000129  0.000000e+00  0.000129  0.000011  8.476017e-06  3.108691e-06   
37  0.000032  0.000000e+00  0.000030  0.000008  4.754137e-06  0.000000e+00   
38  0.000003  0.000000e+00  0.000000  0.000000  0.000000e+00  0.000000e+00   
39  0.000343  1.048779e-06  0.000382  0.000047  9.331533e-06  0.000000e+00   
40  0.000028  0.000000e+00  0.000030  0.000004  4.699156e-06  0.000000e+00   
41  0.000105  0.000000e+00  0.000106  0.000009  6.763957e-06  0.000000e+00   
42  0.000167  6.599825e-07  0.000167  0.000014  6.883745e-06  4.602999e-06   
43  0.000115  0.000000e+00  0.000124  0.000010  7.850431e-06  5.518837e-06   
44  0.000157  0.000000e+00  0.000157  0.000017  0.000000e+00  0.000000e+00   
45  0.000061  2.543672e-07  0.000066  0.000006  1.885118e-06  2.582865e-06   
46  0.000080  0.000000e+00  0.000080  0.000011  5.415133e-06  0.000000e+00   
47  0.000118  0.000000e+00  0.000113  0.000014  0.000000e+00  4.612672e-06   
48  0.000417  4.594909e-06  0.000351  0.000027  1.844510e-05  1.006521e-06   
49  0.000120  0.000000e+00  0.000124  0.000013  3.939430e-06  0.000000e+00   

    6             7      

In [43]:
hap_values_sum_axis0 = np.sum(df_shap_values0to50_bin, axis=0)
hap_values_sum_axis0

0   -4.107953e-06
1   -7.435994e-06
2   -2.561900e-07
3    1.520580e-06
4    5.374354e-06
5   -2.851546e-06
6    3.952963e-06
7    1.135898e-05
8   -4.297067e-06
9   -3.228323e-06
dtype: float64

In [47]:
hap_values_sum_axis0_axis0 = np.sum(hap_values_sum_axis0, axis=0)
hap_values_sum_axis0_axis0

2.9802319056946618e-08

In [49]:
hap_values_sum_axis0_axis1 = np.sum(hap_values_sum_axis0, axis=1)
hap_values_sum_axis0_axis1

ValueError: No axis named 1 for object type Series

In [48]:
hap_values_sum = np.sum(df_shap_values0to50_bin)
hap_values_sum

0   -4.107953e-06
1   -7.435994e-06
2   -2.561900e-07
3    1.520580e-06
4    5.374354e-06
5   -2.851546e-06
6    3.952963e-06
7    1.135898e-05
8   -4.297067e-06
9   -3.228323e-06
dtype: float64

In [40]:
hap_values_abs_sum_axis0 = np.sum(df_shap_values0to50_bin_abs, axis=0)
hap_values_abs_sum_axis0

0    0.005515
1    0.000019
2    0.005538
3    0.000630
4    0.000223
5    0.000056
6    0.000025
7    0.003450
8    0.000013
9    0.001328
dtype: float64

In [42]:
hap_values_abs_sum = np.sum(df_shap_values0to50_bin_abs[0])
hap_values_abs_sum

0.005514640028161402

In [30]:
dfSort = dfTest.sort_values(["Group","ID"])
dfSort

Group Top10Index                           \
0  VI    [15, 6, 8, 7, 4, 5, 13, 10, 18, 9]   
2  VI    [15, 6, 7, 8, 4, 5, 13, 10, 18, 9]   
1  VI    [15, 7, 8, 4, 5, 13, 6, 10, 18, 9]   
3  VI       [20, 9, 1, 2, 3, 4, 5, 6, 7, 8]   
4  VI    [15, 6, 7, 8, 4, 5, 13, 18, 10, 9]   

  Top10Rank                                                       Scaling    \
0       [NIRv, fPAR, MCTI, LAI, EVI, EVI2, NDVI, NDII, SAVI, MSI]  DivBy10K   
2       [NIRv, fPAR, LAI, MCTI, EVI, EVI2, NDVI, NDII, SAVI, MSI]  DivBy10K   
1       [NIRv, LAI, MCTI, EVI, EVI2, NDVI, fPAR, NDII, SAVI, MSI]  DivBy10K   
3  [Albedo, MSI, CAI, CRI550, CRI700, EVI, EVI2, fPAR, LAI, MCTI]  DivBy10K   
4       [NIRv, fPAR, LAI, MCTI, EVI, EVI2, NDVI, SAVI, NDII, MSI]  DivBy10K   

  Randomizer #Bands #Trials Band/Trial MinBands hh:mm:ss.ms     Host(s)   \
0  randitU    21     32      10         10       0:26:36.387707  ilab213   
2  randitU    21     32      10         10       0:26:52.317282  ilab213   
1  randitU    21     32      10         10          0:25:12.317  ilab213   
3  randitU    21     32      10         10       0:26:56.519002  ilab213   
4  randitU    21     32      10         10       0:27:43.264823  ilab213   

  CPUs/Host Concurrency ResultDir                ID                   \
0  30        Pool        VI_randint_U_20240229_5  345536919353575236   
2  30        Pool        VI_randint_U_20240229_3  548764528868727045   
1  30        Pool        VI_randint_U_20240229_4  673843053471350852   
3  30        Pool        VI_randint_U_20240229_2  711241757083075094   
4  30        Pool        VI_randint_U_20240229_1  711241757083075094   

  Description                                                                       \
0  ## VI - ilab213:  Time elapsed on node [ilab213] = (hh:mm:ss.ms) 0:26:36.387707   
2  ## VI - ilab213:  Time elapsed on node [ilab213] = (hh:mm:ss.ms) 0:26:52.317282   
1              ## VI - ilab213:  Time elapsed on node [ilab213] = (hh:mm:ss.ms) ??   
3  ## VI - ilab213:  Time elapsed on node [ilab213] = (hh:mm:ss.ms) 0:26:56.519002   
4  ## VI - ilab213:  Time elapsed on node [ilab213] = (hh:mm:ss.ms) 0:27:43.264823   

  HF                                   Callbacks      
0  MLBS_2018_hyperspectral_indices.tif  EarlyWarning  
2  MLBS_2018_hyperspectral_indices.tif  EarlyWarning  
1  MLBS_2018_hyperspectral_indices.tif  EarlyWarning  
3  MLBS_2018_hyperspectral_indices.tif  EarlyWarning  
4  MLBS_2018_hyperspectral_indices.tif  EarlyWarning