In [1]:
import sys
sys.path.append('/explore/nobackup/people/gtamkin/dev/AGB/mpf-model-factories/MultiPathFusion')
from multi_path_fusion.src.utils.data_generator_helpers import load_data_generator

2023-10-28 12:47:09.657434: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-28 12:47:09.829708: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


In [3]:
from tensorflow import keras
import json
import matplotlib.pyplot as plt
import numpy as np
import mlflow
import rasterio

In [4]:
with open('../../config/config_gt_1model_1band.json', 'r') as f:
    config = json.load(f)
    models_config = config["models"]
    data_generator_config = config["data_generator"]
    mlflow_config = config["mlflow"]

In [8]:
train_generator = load_data_generator(data_generator_config, split_mode='train')

reading in band: 18
reading in band: 14
reading in band: 9
reading in band: 3
reading in band: 20
reading in band: 8
reading in band: 10


In [21]:
print(train_generator.file_x_stack.shape)
print(len(train_generator.file_x_stack[0]))
print(train_generator.file_x_stack[0])
print(train_generator.file_x_stack[1])
print(train_generator.file_x_stack[2])
print(train_generator.file_x_stack[3])
print(train_generator.file_x_stack[4])
print(train_generator.file_x_stack[5])
print(train_generator.file_x_stack[6])

(7, 800000)
800000
[0.         0.00914348 0.00762534 ... 0.         0.         0.        ]
[0.21874148 0.1999218  0.2188757  ... 0.31334597 0.32275727 0.32249138]
[1.         0.99999994 0.99999994 ... 0.99999994 0.99999994 0.99999994]
[0.00217841 0.         0.         ... 0.00703716 0.00864428 0.00371583]
[0.24960981 0.228512   0.25062677 ... 0.39478815 0.3997423  0.39363796]
[0.40140605 0.31169966 0.41021192 ... 0.54478836 0.5819893  0.6397344 ]
[0.09544753 0.0662163  0.07637063 ... 0.26191223 0.25695    0.22452728]


In [22]:
validate_generator = load_data_generator(data_generator_config, 'validate')
print(validate_generator.file_x_stack.shape)
print(len(validate_generator.file_x_stack[0]))
print(validate_generator.file_x_stack[0])
print(validate_generator.file_x_stack[1])
print(validate_generator.file_x_stack[2])
print(validate_generator.file_x_stack[3])
print(validate_generator.file_x_stack[4])
print(validate_generator.file_x_stack[5])
print(validate_generator.file_x_stack[6])

reading in band: 18
reading in band: 14
reading in band: 9
reading in band: 3
reading in band: 20
reading in band: 8
reading in band: 10
(7, 100000)
100000
[0.         0.         0.00353029 ... 0.00310769 0.00152629 0.00317371]
[0.33646894 0.32191247 0.22822113 ... 0.32432133 0.30225524 0.26360014]
[1.         0.99999994 1.         ... 1.         1.         0.99999994]
[4.0234029e-03 4.4464134e-05 0.0000000e+00 ... 0.0000000e+00 0.0000000e+00
 0.0000000e+00]
[0.3902713  0.37067035 0.25534904 ... 0.41413903 0.38353664 0.3287818 ]
[0.67096096 0.65147847 0.30789918 ... 0.5955001  0.5532503  0.4024672 ]
[0.19250262 0.16950335 0.10310959 ... 0.15990072 0.11644876 0.09911121]


In [23]:
test_generator = load_data_generator(data_generator_config, 'test')
print(test_generator.file_x_stack.shape)
print(len(test_generator.file_x_stack[0]))
print(test_generator.file_x_stack[0])
print(test_generator.file_x_stack[1])
print(test_generator.file_x_stack[2])
print(test_generator.file_x_stack[3])
print(test_generator.file_x_stack[4])
print(test_generator.file_x_stack[5])
print(test_generator.file_x_stack[6])

reading in band: 18
reading in band: 14
reading in band: 9
reading in band: 3
reading in band: 20
reading in band: 8
reading in band: 10
(7, 100000)
100000
[0.00425723 0.00456369 0.00605362 ... 0.         0.0001284  0.00178381]
[0.33231062 0.31466985 0.26850963 ... 0.3343295  0.37743014 0.40617245]
[1.         1.         0.99999994 ... 0.99999994 0.99999994 1.        ]
[0.000000e+00 0.000000e+00 0.000000e+00 ... 8.557644e-05 0.000000e+00
 0.000000e+00]
[0.37718162 0.35525632 0.30107415 ... 0.40093535 0.4487777  0.48507217]
[0.9737624  0.750765   0.8045844  ... 0.8480241  0.93982977 0.89399654]
[0.17025279 0.16147678 0.12919019 ... 0.22392356 0.2412937  0.28305784]


In [56]:
print('\ntrain_generator')
print(len(train_generator.binned))
print(train_generator.binned)
print(train_generator.binned[799999])
print(train_generator.branch_inputs[0][0])

print('\ntest_generator')
print(len(test_generator.binned))
print(test_generator.binned)
print(test_generator.binned[99999])
print(test_generator.branch_inputs)

print('\nvalidate_generator')
print(len(validate_generator.binned))
print(validate_generator.binned[99999])
print(validate_generator.binned)
print(validate_generator.branch_inputs)


train_generator
800000
[2 3 3 ... 4 2 1]
1
['MLBS_2018_541567.6_4136443.0_542567.6_4137443.0/MLBS_2018_hyperspectral_indices.tif', array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
    

In [57]:
X_full_hyperspectral = train_generator.get_training_data()
print(X_full_hyperspectral.shape)

(800000, 7)


In [59]:
#print(train_generator.branch_inputs)
file_num = 0
for branch_num in range(len(train_generator.branch_inputs)):
    print(len(train_generator.branch_inputs[branch_num][file_num]))
    print(f"branch_num: {branch_num}")
    for file_num in range(len(train_generator.branch_inputs[branch_num])):
        print(f"file_num: {file_num}")
        print('before')
        print(train_generator.branch_inputs[branch_num][file_num][1])
        # changing bands to full hyperspectral image
        train_generator.branch_inputs[branch_num][file_num][1] = np.arange(426)
        print('after')
        print(train_generator.branch_inputs[branch_num][file_num][1])


2
branch_num: 0
file_num: 0
before
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237

In [60]:
X = train_generator.get_training_data()

In [62]:
print(X)
print(np.min(X))
print(np.max(X))
print(X.shape)

[[0.         0.21874148 1.         ... 0.24960981 0.40140605 0.09544753]
 [0.00914348 0.1999218  0.99999994 ... 0.228512   0.31169966 0.0662163 ]
 [0.00762534 0.2188757  0.99999994 ... 0.25062677 0.41021192 0.07637063]
 ...
 [0.         0.31334597 0.99999994 ... 0.39478815 0.54478836 0.26191223]
 [0.         0.32275727 0.99999994 ... 0.3997423  0.5819893  0.25695   ]
 [0.         0.32249138 0.99999994 ... 0.39363796 0.6397344  0.22452728]]
0.0
1.0000001
(800000, 7)


In [63]:
print("before scaling")
print(train_generator.file_x_stack)
print(train_generator.file_x_stack.shape)
print(f"min: {np.min(train_generator.file_x_stack)}")
print(f"max: {np.max(train_generator.file_x_stack)}")
print(f"avg: {np.average(train_generator.file_x_stack)}")
print(f"std: {np.std(train_generator.file_x_stack)}")
train_generator.file_x_stack = train_generator.scale_data(train_generator.file_x_stack)
print("after scaling")
print(train_generator.file_x_stack)
print(train_generator.file_x_stack.shape)
print(f"min: {np.min(train_generator.file_x_stack)}")
print(f"max: {np.max(train_generator.file_x_stack)}")
print(f"avg: {np.average(train_generator.file_x_stack)}")
print(f"std: {np.std(train_generator.file_x_stack)}")

before scaling
[[0.         0.00914348 0.00762534 ... 0.         0.         0.        ]
 [0.21874148 0.1999218  0.2188757  ... 0.31334597 0.32275727 0.32249138]
 [1.         0.99999994 0.99999994 ... 0.99999994 0.99999994 0.99999994]
 ...
 [0.24960981 0.228512   0.25062677 ... 0.39478815 0.3997423  0.39363796]
 [0.40140605 0.31169966 0.41021192 ... 0.54478836 0.5819893  0.6397344 ]
 [0.09544753 0.0662163  0.07637063 ... 0.26191223 0.25695    0.22452728]]
(7, 800000)
min: 0.0
max: 1.0000001192092896
avg: 0.34291598200798035
std: 0.3424108922481537
after scaling
[[0.         0.00914348 0.00762534 ... 0.         0.         0.        ]
 [0.21874148 0.19992183 0.21887574 ... 0.313346   0.3227573  0.3224914 ]
 [1.         1.         1.         ... 1.         1.         1.        ]
 ...
 [0.24960981 0.22851203 0.2506268  ... 0.3947882  0.39974236 0.393638  ]
 [0.40140605 0.3116997  0.41021198 ... 0.5447884  0.58198935 0.63973445]
 [0.09544753 0.06621631 0.07637064 ... 0.26191226 0.25695002 0.

In [67]:
# normalizing training data using sklearn
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler(feature_range=(0,1))
#min_max_scaler = MinMaxScaler(feature_range=(-1,1))
normalized_X = min_max_scaler.fit_transform(X)

In [68]:
print(train_generator.scale_data_method)
if train_generator.scale_data_method:
    print("normalize")
else:
    print("None")

minmax
normalize


In [69]:
print(X)
print(normalized_X)

[[0.         0.21874148 1.         ... 0.24960981 0.40140605 0.09544753]
 [0.00914348 0.1999218  0.99999994 ... 0.228512   0.31169966 0.0662163 ]
 [0.00762534 0.2188757  0.99999994 ... 0.25062677 0.41021192 0.07637063]
 ...
 [0.         0.31334597 0.99999994 ... 0.39478815 0.54478836 0.26191223]
 [0.         0.32275727 0.99999994 ... 0.3997423  0.5819893  0.25695   ]
 [0.         0.32249138 0.99999994 ... 0.39363796 0.6397344  0.22452728]]
[[0.         0.21825284 0.9999999  ... 0.24063319 0.401406   0.08643602]
 [0.0091588  0.19940048 0.9999998  ... 0.219283   0.31169963 0.05691358]
 [0.00763812 0.21838729 0.9999998  ... 0.24166232 0.41021186 0.06716907]
 ...
 [0.         0.3130216  0.9999998  ... 0.3875482  0.5447883  0.25455907]
 [0.         0.32244924 0.9999998  ... 0.39256164 0.5819892  0.2495474 ]
 [0.         0.32218286 0.9999998  ... 0.38638428 0.6397343  0.2168017 ]]


In [70]:
# normalizing training data
def normalize_pixels(training_data):
    max_val = np.max(training_data, axis=0)
    normalized_data = training_data / max_val
    return normalized_data

normalized_X = normalize_pixels(X)

In [71]:
print(normalized_X)
print(normalized_X.shape)

[[0.         0.21893115 0.9999999  ... 0.24960978 0.401406   0.09544752]
 [0.0091588  0.20009516 0.9999998  ... 0.22851197 0.31169963 0.0662163 ]
 [0.00763812 0.21906549 0.9999998  ... 0.25062674 0.41021186 0.07637063]
 ...
 [0.         0.31361768 0.9999998  ... 0.3947881  0.5447883  0.2619122 ]
 [0.         0.32303715 0.9999998  ... 0.39974225 0.5819892  0.25694996]
 [0.         0.322771   0.9999998  ... 0.3936379  0.6397343  0.22452725]]
(800000, 7)


In [72]:
print(normalized_X)
print(np.max(normalized_X))
print(np.min(normalized_X))

[[0.         0.21893115 0.9999999  ... 0.24960978 0.401406   0.09544752]
 [0.0091588  0.20009516 0.9999998  ... 0.22851197 0.31169963 0.0662163 ]
 [0.00763812 0.21906549 0.9999998  ... 0.25062674 0.41021186 0.07637063]
 ...
 [0.         0.31361768 0.9999998  ... 0.3947881  0.5447883  0.2619122 ]
 [0.         0.32303715 0.9999998  ... 0.39974225 0.5819892  0.25694996]
 [0.         0.322771   0.9999998  ... 0.3936379  0.6397343  0.22452725]]
1.0
0.0


In [73]:
X

array([[0.        , 0.21874148, 1.        , ..., 0.24960981, 0.40140605,
        0.09544753],
       [0.00914348, 0.1999218 , 0.99999994, ..., 0.228512  , 0.31169966,
        0.0662163 ],
       [0.00762534, 0.2188757 , 0.99999994, ..., 0.25062677, 0.41021192,
        0.07637063],
       ...,
       [0.        , 0.31334597, 0.99999994, ..., 0.39478815, 0.54478836,
        0.26191223],
       [0.        , 0.32275727, 0.99999994, ..., 0.3997423 , 0.5819893 ,
        0.25695   ],
       [0.        , 0.32249138, 0.99999994, ..., 0.39363796, 0.6397344 ,
        0.22452728]], dtype=float32)

In [74]:
y = train_generator.get_truth_vals()

In [75]:
y

array([2., 3., 3., ..., 4., 2., 1.])

In [76]:
def log_truth_proportions(data_generator):
    y = data_generator.get_truth_vals()
    bins, counts = np.unique(y, return_counts=True)
    proportions = counts / len(y)

    for bin, proportion in zip(bins, proportions):
        print(f"Bin {bin}: {proportion*100:.2f}%")

In [78]:
print(y)
print(len(y))
print(np.max(y))
print(np.min(y))
print(np.unique(y, return_counts=True))


[2. 3. 3. ... 4. 2. 1.]
800000
4.0
0.0
(array([0., 1., 2., 3., 4.]), array([192105, 117764, 222180, 184522,  83429]))


In [79]:
log_truth_proportions(train_generator)

Bin 0.0: 24.01%
Bin 1.0: 14.72%
Bin 2.0: 27.77%
Bin 3.0: 23.07%
Bin 4.0: 10.43%


In [80]:
print(y)

[2. 3. 3. ... 4. 2. 1.]


In [81]:
normalized_y = normalize_pixels(y)

In [82]:
print(normalized_y)
print(np.max(normalized_y))
print(np.min(normalized_y))

[0.5  0.75 0.75 ... 1.   0.5  0.25]
1.0
0.0


In [83]:
bins_0 = np.count_nonzero(y == 0)
print(bins_0)
bins_1 = np.count_nonzero(y == 1)
print(bins_1)
bins_2 = np.count_nonzero(y == 2)
print(bins_2)
bins_3 = np.count_nonzero(y == 3)
print(bins_3)
bins_4 = np.count_nonzero(y == 4)
print(bins_4)
bins_5 = np.count_nonzero(y == 5)
print(bins_5)

192105
117764
222180
184522
83429
0


In [84]:
bins_0_percent = np.count_nonzero(y == 0) / len(y)
print(bins_0_percent)
bins_1_percent = np.count_nonzero(y == 1) / len(y)
print(bins_1_percent)
bins_2_percent = np.count_nonzero(y == 2) / len(y)
print(bins_2_percent)
bins_3_percent = np.count_nonzero(y == 3) / len(y)
print(bins_3_percent)
bins_4_percent = np.count_nonzero(y == 4) / len(y)
print(bins_4_percent)
bins_5_percent = np.count_nonzero(y == 5) / len(y)
print(bins_5_percent)

0.24013125
0.147205
0.277725
0.2306525
0.10428625
0.0


In [86]:
# print(train_generator[0])
# print(train_generator[0].shape)
x, y = train_generator[0]
print(x)
print(x.shape)
print(y)
print(y.shape)

[[0.00000000e+00 2.18741477e-01 1.00000000e+00 2.17841333e-03
  2.49609813e-01 4.01406050e-01 9.54475328e-02]
 [9.14347824e-03 1.99921831e-01 1.00000000e+00 0.00000000e+00
  2.28512034e-01 3.11699688e-01 6.62163123e-02]
 [7.62534235e-03 2.18875736e-01 1.00000000e+00 0.00000000e+00
  2.50626802e-01 4.10211980e-01 7.63706416e-02]
 [5.24572795e-03 2.86141038e-01 1.00000000e+00 0.00000000e+00
  3.23433876e-01 9.71112549e-01 1.18927665e-01]
 [3.02418647e-03 1.60404935e-01 4.80374455e-01 0.00000000e+00
  1.80504546e-01 1.00000000e+00 7.55406022e-02]
 [3.46051971e-03 1.47425473e-01 4.45894122e-01 0.00000000e+00
  1.65480942e-01 1.00000000e+00 7.11755604e-02]
 [5.09469677e-03 1.81433633e-01 5.68702102e-01 0.00000000e+00
  2.03123480e-01 1.00000000e+00 8.74024704e-02]
 [6.76979590e-03 2.59662390e-01 1.00000000e+00 0.00000000e+00
  2.93149531e-01 8.77770662e-01 1.12459905e-01]
 [7.51874968e-03 2.01480120e-01 1.00000000e+00 0.00000000e+00
  2.31240883e-01 3.86830688e-01 7.76062608e-02]
 [7.333982

In [89]:
def log_params(params, parent_key=''):
    for k, v in params.items():
        new_key = f"{parent_key} / {k}" if parent_key else k
        if isinstance(v, dict):
            log_params(v, new_key)
        elif isinstance(v, list):
            for i, item in enumerate(v):
                if isinstance(item, dict):
                    log_params(item, f"{new_key} / {i+1}")
                else:
                    print(f"{new_key} / {i+1}", item)
        else:
            print(new_key, v)

In [90]:
def log_params(params, parent_key=''):
    for k, v in params.items():
        new_key = f"{parent_key} / {k}" if parent_key else k
        if isinstance(v, dict):
            for key, value in v.items():
                mlflow.log_param(f"{key}", value)
        elif isinstance(v, list):
            for i, item in enumerate(v):
                if isinstance(item, dict):
                    log_params(item, f"{new_key} / {i+1}")
                else:
                    mlflow.log_param(f"{new_key} / {i+1}", item)
        else:
            mlflow.log_param(new_key, v)


In [91]:
for model_config in models_config:
    log_params(model_config)
    print(" NEXT MODEL ")

 NEXT MODEL 
